In [1]:
import pandas as pd
import numpy as np

file_path = "yellow_tripdata_2024-01.parquet"
df = pd.read_parquet(file_path)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[us](2), float64(12), int32(3), int64(1), object(1)
memory usage: 395.8+ MB

In [3]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2.964624e+06,2964624,2964624,2.824462e+06,2.964624e+06,2.824462e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.824462e+06,2.824462e+06
mean,1.754204e+00,2024-01-17 00:46:36.431092,2024-01-17 01:02:13.208130,1.339281e+00,3.652169e+00,2.069359e+00,1.660179e+02,1.651167e+02,1.161271e+00,1.817506e+01,1.451598e+00,4.833823e-01,3.335870e+00,5.270212e-01,9.756319e-01,2.680150e+01,2.256122e+00,1.411611e-01
min,1.000000e+00,2002-12-31 22:59:39,2002-12-31 23:05:41,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-8.990000e+02,-7.500000e+00,-5.000000e-01,-8.000000e+01,-8.000000e+01,-1.000000e+00,-9.000000e+02,-2.500000e+00,-1.750000e+00
25%,2.000000e+00,2024-01-09 15:59:19.750000,2024-01-09 16:16:23,1.000000e+00,1.000000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.000000e+00,0.000000e+00,1.000000e+00,1.538000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2024-01-17 10:45:37.500000,2024-01-17 11:03:51.500000,1.000000e+00,1.680000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.280000e+01,1.000000e+00,5.000000e-01,2.700000e+00,0.000000e+00,1.000000e+00,2.010000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2024-01-24 18:23:52.250000,2024-01-24 18:40:29,1.000000e+00,3.110000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,2.050000e+01,2.500000e+00,5.000000e-01,4.120000e+00,0.000000e+00,1.000000e+00,2.856000e+01,2.500000e+00,0.000000e+00
max,6.000000e+00,2024-02-01 00:01:15,2024-02-02 13:56:52,9.000000e+00,3.127223e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,5.000000e+03,1.425000e+01,4.000000e+00,4.280000e+02,1.159200e+02,1.000000e+00,5.000000e+03,2.500000e+00,1.750000e+00
std,4.325902e-01,NaN,NaN,8.502817e-01,2.254626e+02,9.823219e+00,6.362391e+01,6.931535e+01,5.808686e-01,1.894955e+01,1.804102e+00,1.177600e-01,3.896551e+00,2.128310e+00,2.183645e-01,2.338558e+01,8.232747e-01,4.876239e-01

In [4]:
df.head(50)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.00,0.5,0.00,0.00,1.0,22.70,2.5,0.00
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.50,0.5,3.75,0.00,1.0,18.75,2.5,0.00
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.50,0.5,3.00,0.00,1.0,31.30,2.5,0.00
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.50,0.5,2.00,0.00,1.0,17.00,2.5,0.00
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.50,0.5,3.20,0.00,1.0,16.10,2.5,0.00
5,1,2024-01-01 00:54:08,2024-01-01 01:26:31,1.0,4.70,1.0,N,148,141,1,29.6,3.50,0.5,6.90,0.00,1.0,41.50,2.5,0.00
6,2,2024-01-01 00:49:44,2024-01-01 01:15:47,2.0,10.82,1.0,N,138,181,1,45.7,6.00,0.5,10.00,0.00,1.0,64.95,0.0,1.75
7,1,2024-01-01 00:30:40,2024-01-01 00:58:40,0.0,3.00,1.0,N,246,231,2,25.4,3.50,0.5,0.00,0.00,1.0,30.40,2.5,0.00
8,2,2024-01-01 00:26:01,2024-01-01 00:54:12,1.0,5.44,1.0,N,161,261,2,31.0,1.00,0.5,0.00,0.00,1.0,36.00,2.5,0.00
9,2,2024-01-01 00:28:08,2024-01-01 00:29:16,1.0,0.04,1.0,N,113,113,2,3.0,1.00,0.5,0.00,0.00,1.0,8.00,2.5,0.00
10,2,2024-01-01 00:35:22,2024-01-01 00:41:41,2.0,0.75,1.0,N,107,137,1,7.9,1.00,0.5,0.00,0.00,1.0,12.90,2.5,0.00
11,1,2024-01-01 00:25:00,2024-01-01 00:34:03,2.0,1.20,1.0,N,158,246,1,14.9,3.50,0.5,3.95,0.00,1.0,23.85,2.5,0.00
12,1,2024-01-01 00:35:16,2024-01-01 01:11:52,2.0,8.20,1.0,N,246,190,1,59.0,3.50,0.5,14.15,6.94,1.0,85.09,2.5,0.00
13,1,2024-01-01 00:43:27,2024-01-01 00:47:11,2.0,0.40,1.0,N,68,90,1,5.8,3.50,0.5,1.25,0.00,1.0,12.05,2.5,0.00
14,1,2024-01-01 00:51:53,2024-01-01 00:55:43,1.0,0.80,1.0,N,90,68,2,6.5,3.50,0.5,0.00,0.00,1.0,11.50,2.5,0.00
15,1,2024-01-01 00:50:09,2024-01-01 01:03:57,1.0,5.00,1.0,N,132,216,2,21.2,2.75,0.5,0.00,0.00,1.0,25.45,0.0,1.75
16,1,2024-01-01 00:41:06,2024-01-01 00:53:42,1.0,1.50,1.0,N,164,79,1,12.8,3.50,0.5,4.45,0.00,1.0,22.25,2.5,0.00
17,2,2024-01-01 00:52:09,2024-01-01 00:52:28,1.0,0.00,1.0,N,237,237,2,3.0,1.00,0.5,0.00,0.00,1.0,8.00,2.5,0.00
18,2,2024-01-01 00:56:38,2024-01-01 01:03:17,1.0,1.50,1.0,N,141,263,1,9.3,1.00,0.5,3.00,0.00,1.0,17.30,2.5,0.00
19,2,2024-01-01 00:32:34,2024-01-01 00:49:33,1.0,2.57,1.0,N,161,263,1,17.7,1.00,0.5,10.00,0.00,1.0,32.70,2.5,0.00
20,2,2024-01-01 00:52:30,2024-01-01 00:57:37,1.0,0.66,1.0,N,263,236,1,6.5,1.00,0.5,2.88,0.00,1.0,14.38,2.5,0.00
21,1,2024-01-01 00:36:30,2024-01-01 01:13:53,2.0,1.70,1.0,N,246,170,1,29.6,3.50,0.5,6.90,0.00,1.0,41.50,2.5,0.00
22,2,2024-01-01 00:44:24,2024-01-01 00:51:57,1.0,0.94,1.0,N,158,113,1,8.6,1.00,0.5,2.72,0.00,1.0,16.32,2.5,0.00
23,1,2024-01-01 00:14:29,2024-01-01 00:14:29,1.0,0.00,1.0,N,236,264,2,3.0,3.50,0.5,0.00,0.00,1.0,8.00,2.5,0.00
24,1,2024-01-01 00:42:05,2024-01-01 01:16:49,1.0,23.90,5.0,N,263,265,1,120.0,0.00,0.0,0.00,6.94,1.0,127.94,0.0,0.00
25,2,2024-01-01 00:12:35,2024-01-01 00:19:21,2.0,1.08,1.0,N,148,4,1,8.6,1.00,0.5,2.72,0.00,1.0,16.32,2.5,0.00
26,2,2024-01-01 00:20:11,2024-01-01 00:42:53,1.0,5.88,1.0,N,4,238,1,28.9,1.00,0.5,2.50,0.00,1.0,36.40,2.5,0.00
27,2,2024-01-01 00:44:01,2024-01-01 00:54:31,2.0,2.22,1.0,N,238,50,1,13.5,1.00,0.5,0.00,0.00,1.0,18.50,2.5,0.00
28,1,2024-01-01 00:08:12,2024-01-01 00:41:08,1.0,5.10,1.0,N,239,114,2,28.9,3.50,0.5,0.00,0.00,1.0,33.90,2.5,0.00
29,2,2024-01-01 00:36:25,2024-01-01 00:47:26,2.0,2.09,1.0,N,233,79,1,12.8,1.00,0.5,3.56,0.00,1.0,21.36,2.5,0.00
30,2,2024-01-01 00:49:31,2024-01-01 01:35:41,2.0,8.89,1.0,N,79,41,1,47.8,1.00,0.5,7.92,0.00,1.0,60.72,2.5,0.00
31,1,2024-01-01 00:15:34,2024-01-01 00:28:51,2.0,2.10,1.0,N,162,143,1,14.2,3.50,0.5,3.80,0.00,1.0,23.00,2.5,0.00
32,2,2024-01-01 00:15:26,2024-01-01 00:33:57,1.0,11.51,1.0,N,262,171,1,44.3,1.00,0.5,11.25,6.94,1.0,67.49,2.5,0.00
33,2,2024-01-01 00:18:36,2024-01-01 00:40:49,1.0,1.79,1.0,N,239,68,2,19.8,1.00,0.5,0.00,0.00,1.0,24.80,2.5,0.00
34,1,2024-01-01 00:09:17,2024-01-01 00:16:55,2.0,2.50,1.0,N,137,140,2,12.1,3.50,0.5,0.00,0.00,1.0,17.10,2.5,0.00
35,1,2024-01-01 00:21:40,2024-01-01 00:27:05,1.0,1.60,1.0,N,140,229,1,9.3,3.50,0.5,3.55,0.00,1.0,17.85,2.5,0.00
36,1,2024-01-01 00:39:03,2024-01-01 00:44:28,4.0,1.10,1.0,N,236,238,1,7.9,3.50,0.5,0.00,0.00,1.0,12.90,2.5,0.00
37,1,2024-01-01 00:45:51,2024-01-01 00:49:43,2.0,0.70,1.0,N,238,142,1,6.5,3.50,0.5,2.30,0.00,1.0,13.80,2.5,0.00
38,1,2024-01-01 00:50:46,2024-01-01 00:57:26,2.0,1.10,1.0,N,142,239,4,8.6,3.50,0.5,0.00,0.00,1.0,13.60,2.5,0.00
39,2,2024-01-01 00:09:49,2024-01-01 00:22:00,1.0,2.96,1.0,N,229,249,1,14.9,1.00,0.5,3.98,0.00,1.0,23.88,2.5,0.00
40,2,2024-01-01 00:36:44,2024-01-01 00:54:40,1.0,1.20,1.0,N,186,48,1,16.3,1.00,0.5,4.26,0.00,1.0,25.56,2.5,0.00
41,2,2024-01-01 00:58:11,2024-01-01 01:24:47,1.0,2.42,1.0,N,68,125,1,23.3,1.00,0.5,0.00,0.00,1.0,28.30,2.5,0.00
42,2,2024-01-01 00:24:41,2024-01-01 00:54:01,1.0,5.28,1.0,N,113,238,1,31.0,1.00,0.5,7.20,0.00,1.0,43.20,2.5,0.00
43,2,2024-01-01 00:55:58,2024-01-01 01:03:54,1.0,1.47,1.0,N,238,142,1,10.0,1.00,0.5,2.00,0.00,1.0,17.00,2.5,0.00
44,2,2024-01-01 00:19:36,2024-01-01 00:31:57,3.0,2.41,1.0,N,239,236,1,14.2,1.00,0.5,3.84,0.00,1.0,23.04,2.5,0.00
45,2,2024-01-01 00:45:44,2024-01-01 00:51:25,4.0,1.04,1.0,N,142,163,2,7.9,1.00,0.5,0.00,0.00,1.0,12.90,2.5,0.00
46,2,2024-01-01 00:55:21,2024-01-01 01:12:17,4.0,2.41,1.0,N,163,140,1,17.7,1.00,0.5,4.54,0.00,1.0,27.24,2.5,0.00
47,2,2024-01-01 00:05:45,2024-01-01 00:17:29,1.0,1.06,1.0,N,246,90,2,11.4,1.00,0.5,0.00,0.00,1.0,16.40,2.5,0.00
48,2,2024-01-01 00:18:38,2024-01-01 00:26:09,1.0,0.83,1.0,N,234,170,1,8.6,1.00,0.5,3.40,0.00,1.0,17.00,2.5,0.00
49,2,2024-01-01 00:38:58,2024-01-01 00:53:37,1.0,1.94,1.0,N,114,79,1,14.9,1.00,0.5,3.98,0.00,1.0,23.88,2.5,0.00

In [5]:
df.isna().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          140162
trip_distance                 0
RatecodeID               140162
store_and_fwd_flag       140162
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     140162
Airport_fee              140162
dtype: int64

In [6]:
print(df['payment_type'].value_counts())

payment_type
1    2319046
2     439191
0     140162
4      46628
3      19597
Name: count, dtype: int64

In [7]:
# Error Logging Setup
# Initialize an empty DataFrame to store isolated error records with reason tags

df_errors = pd.DataFrame()

In [8]:
# Passenger Count Cleaning (passenger_count)
# Fill missing passenger values with the default (1) and convert to integer

df['passenger_count'] = df['passenger_count'].fillna(1).astype(int)

In [9]:
# Isolate invalid passenger counts (< 1 or > 6)
invalid_passengers = df[(df["passenger_count"] < 1) | (df["passenger_count"] > 6)].copy()
invalid_passengers["error_reason"] = "Invalid Passenger Count (<1 or >6)"
df_errors = pd.concat([df_errors, invalid_passengers])
df = df.drop(index=invalid_passengers.index)

In [10]:
# Payment Type Cleaning (payment_type)
# Replace implicit null value 0 with 5 (Unknown, per NYC Taxi dataset dictionary)
df['payment_type']= df['payment_type'].replace(0,5)

In [11]:
# Isolate voided trips (payment_type == 6)
invalid_payments = df[df["payment_type"] == 6].copy()
invalid_payments["error_reason"]="Voided Trip (payment_type == 6)"
# Append to errors DataFrame and drop from main clean DataFrame
df_errors = pd.concat([df_errors ,invalid_payments ])
df = df.drop(index=invalid_payments.index)

In [12]:
# Rate Code Cleaning (RatecodeID)
# Fill missing values with default 1 (Standard Rate) and cast to integer

df['RatecodeID']=df['RatecodeID'].fillna(1).astype(int)

In [13]:
df['RatecodeID'].value_counts()

RatecodeID
1     2773215
2       97953
99      28629
5       19110
3        7864
4        6321
6           7
Name: count, dtype: int64

In [14]:
# Isolate invalid rate codes (values > 6, such as code 99)
invalid_rate=df[df['RatecodeID']>6].copy()
invalid_rate["error_reason"]="Invalid RatecodeID (> 6)"
# Append to errors DataFrame and drop from main clean DataFrame
df_errors=pd.concat([df_errors,invalid_rate])
df=df.drop(index=invalid_rate.index)

In [15]:
# Financial Columns Cleaning (fare_amount & total_amount)
# Isolate records with negative or zero fare/total amounts

invalid_amount = df[(df['total_amount']<=0) | (df['fare_amount']<=0)].copy()
invalid_amount["error_reason"]= "Negative or Zero Fare"
# Append to errors DataFrame and drop from main clean DataFrame
df_errors = pd.concat([df_errors , invalid_amount])
df=df.drop(index=invalid_amount.index)

In [16]:
# Datetime & Logical Time Validation
# Isolate records where dropoff timestamp is before or equal to pickup timestamp
invalid_time=df[df['tpep_dropoff_datetime']<=df["tpep_pickup_datetime"]].copy()
invalid_time["error_reason"]= "Dropoff before or equal to Pickup time"
df_errors =pd.concat([df_errors , invalid_time])

df=df.drop(index=invalid_time.index)

In [17]:
# Trip Distance Cleaning (trip_distance)
# Isolate trips with distance <= 0
invalid_distance= df[df['trip_distance']<=0].copy()
invalid_distance["error_reason"]="Invalid Distance (<= 0)"
df_errors=pd.concat([df_errors,invalid_distance])
df=df.drop(index=invalid_distance.index)

In [18]:
# Isolate out-of-range dates (pickups outside of January 2024)
invalid_dates = df[(df["tpep_pickup_datetime"] < "2024-01-01") | (df["tpep_pickup_datetime"] >= "2024-02-01")].copy()
invalid_dates["error_reason"] = "Out of Range Pickup Date (Not Jan 2024)"
df_errors = pd.concat([df_errors, invalid_dates])
df = df.drop(index=invalid_dates.index)

In [19]:
# Remaining Null Values Handling
# Impute missing location IDs with 265 (Unknown Location Code) and cast to integer
df["PULocationID"] = df["PULocationID"].fillna(265).astype(int)
df["DOLocationID"] = df["DOLocationID"].fillna(265).astype(int)
# Impute missing VendorID and store_and_fwd_flag with sensible defaults
df["VendorID"] = df["VendorID"].fillna(1).astype(int)
df["store_and_fwd_flag"] = df["store_and_fwd_flag"].fillna("N")

In [20]:
df.head(20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1,1.72,1,N,186,79,2,17.7,1.00,0.5,0.00,0.00,1.0,22.70,2.5,0.00
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1,1.80,1,N,140,236,1,10.0,3.50,0.5,3.75,0.00,1.0,18.75,2.5,0.00
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1,4.70,1,N,236,79,1,23.3,3.50,0.5,3.00,0.00,1.0,31.30,2.5,0.00
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1,1.40,1,N,79,211,1,10.0,3.50,0.5,2.00,0.00,1.0,17.00,2.5,0.00
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1,0.80,1,N,211,148,1,7.9,3.50,0.5,3.20,0.00,1.0,16.10,2.5,0.00
5,1,2024-01-01 00:54:08,2024-01-01 01:26:31,1,4.70,1,N,148,141,1,29.6,3.50,0.5,6.90,0.00,1.0,41.50,2.5,0.00
6,2,2024-01-01 00:49:44,2024-01-01 01:15:47,2,10.82,1,N,138,181,1,45.7,6.00,0.5,10.00,0.00,1.0,64.95,0.0,1.75
8,2,2024-01-01 00:26:01,2024-01-01 00:54:12,1,5.44,1,N,161,261,2,31.0,1.00,0.5,0.00,0.00,1.0,36.00,2.5,0.00
9,2,2024-01-01 00:28:08,2024-01-01 00:29:16,1,0.04,1,N,113,113,2,3.0,1.00,0.5,0.00,0.00,1.0,8.00,2.5,0.00
10,2,2024-01-01 00:35:22,2024-01-01 00:41:41,2,0.75,1,N,107,137,1,7.9,1.00,0.5,0.00,0.00,1.0,12.90,2.5,0.00
11,1,2024-01-01 00:25:00,2024-01-01 00:34:03,2,1.20,1,N,158,246,1,14.9,3.50,0.5,3.95,0.00,1.0,23.85,2.5,0.00
12,1,2024-01-01 00:35:16,2024-01-01 01:11:52,2,8.20,1,N,246,190,1,59.0,3.50,0.5,14.15,6.94,1.0,85.09,2.5,0.00
13,1,2024-01-01 00:43:27,2024-01-01 00:47:11,2,0.40,1,N,68,90,1,5.8,3.50,0.5,1.25,0.00,1.0,12.05,2.5,0.00
14,1,2024-01-01 00:51:53,2024-01-01 00:55:43,1,0.80,1,N,90,68,2,6.5,3.50,0.5,0.00,0.00,1.0,11.50,2.5,0.00
15,1,2024-01-01 00:50:09,2024-01-01 01:03:57,1,5.00,1,N,132,216,2,21.2,2.75,0.5,0.00,0.00,1.0,25.45,0.0,1.75
16,1,2024-01-01 00:41:06,2024-01-01 00:53:42,1,1.50,1,N,164,79,1,12.8,3.50,0.5,4.45,0.00,1.0,22.25,2.5,0.00
18,2,2024-01-01 00:56:38,2024-01-01 01:03:17,1,1.50,1,N,141,263,1,9.3,1.00,0.5,3.00,0.00,1.0,17.30,2.5,0.00
19,2,2024-01-01 00:32:34,2024-01-01 00:49:33,1,2.57,1,N,161,263,1,17.7,1.00,0.5,10.00,0.00,1.0,32.70,2.5,0.00
20,2,2024-01-01 00:52:30,2024-01-01 00:57:37,1,0.66,1,N,263,236,1,6.5,1.00,0.5,2.88,0.00,1.0,14.38,2.5,0.00
21,1,2024-01-01 00:36:30,2024-01-01 01:13:53,2,1.70,1,N,246,170,1,29.6,3.50,0.5,6.90,0.00,1.0,41.50,2.5,0.00

In [21]:
pd.set_option("display.float_format", lambda x: "%.2f" % x)
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2811758.00,2811758,2811758,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2811758.00,2696563.00,2696563.00
mean,1.77,2024-01-17 01:26:27.515401,2024-01-17 01:41:55.809483,1.34,3.70,1.06,166.62,165.65,1.34,18.37,1.49,0.50,3.44,0.54,1.00,27.29,2.35,0.15
min,1.00,2024-01-01 00:00:00,2024-01-01 00:02:42,1.00,0.01,1.00,1.00,1.00,1.00,0.01,-2.50,0.00,0.00,0.00,0.00,1.01,0.00,0.00
25%,2.00,2024-01-09 16:20:04,2024-01-09 16:37:16.250000,1.00,1.01,1.00,132.00,114.00,1.00,8.60,0.00,0.50,1.00,0.00,1.00,15.48,2.50,0.00
50%,2.00,2024-01-17 10:59:40,2024-01-17 11:17:50.500000,1.00,1.70,1.00,162.00,162.00,1.00,12.80,1.00,0.50,2.80,0.00,1.00,20.15,2.50,0.00
75%,2.00,2024-01-24 18:36:12.750000,2024-01-24 18:51:55.750000,1.00,3.12,1.00,234.00,234.00,1.00,19.80,2.50,0.50,4.20,0.00,1.00,28.55,2.50,0.00
max,6.00,2024-01-31 23:59:55,2024-02-01 22:04:34,6.00,312722.30,6.00,265.00,265.00,5.00,2221.30,14.25,4.00,422.70,115.92,1.00,2225.30,2.50,1.75
std,0.42,NaN,NaN,0.83,231.51,0.33,63.26,69.12,0.88,17.26,1.79,0.04,3.84,2.11,0.01,21.80,0.60,0.49

In [22]:
# Additional Negative Values Check (Surcharges, Taxes, Tips, Tolls)
# Identify financial columns that should not contain negative values
financial_cols = [
    "extra", "mta_tax", "tip_amount", "tolls_amount", 
    "improvement_surcharge", "congestion_surcharge", "Airport_fee"
]
# Create condition for any negative values in these financial fields
neg_condition = (df[financial_cols] < 0).any(axis=1)
invalid_negatives = df[neg_condition].copy()
invalid_negatives["error_reason"] = "Negative values found in surcharge/tax/tip/toll fields"

df_errors = pd.concat([df_errors, invalid_negatives])
df = df.drop(index=invalid_negatives.index)

In [23]:
# Extreme Outliers Filtering (> $5,000)
# Isolate unrealistically high total or fare amounts
extreme_outliers = df[(df["total_amount"] > 5000) | (df["fare_amount"] > 5000)].copy()
extreme_outliers["error_reason"] = "Extreme Outlier Fare/Total Amount (> $5,000)"

df_errors = pd.concat([df_errors, extreme_outliers])
df = df.drop(index=extreme_outliers.index)

In [24]:
#  Trip Duration Calculation & Ultra-Short Trips Handling (< 10 seconds)
# Calculate trip duration in seconds for logical validation
trip_duration_seconds = (df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]).dt.total_seconds()

# Isolate trips that lasted less than 10 seconds (Unrealistic / System Glitch)
short_trips = df[trip_duration_seconds < 10].copy()
short_trips["error_reason"] = "Unrealistic Trip Duration (< 10 seconds)"

df_errors = pd.concat([df_errors, short_trips])
df = df.drop(index=short_trips.index)

In [25]:
# 13. Create New Feature Column (trip_duration_min)
# Add a clean, calculated feature for trip duration in minutes for downstream analysis
df["trip_duration_min"] = (
    (df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]).dt.total_seconds() / 60.0
).round(2)

In [26]:
df["pickup_day_name"] = df["tpep_pickup_datetime"].dt.day_name()
df["is_weekend"] = df["tpep_pickup_datetime"].dt.dayofweek.isin([5, 6]).astype(int)
duration_hours = df["trip_duration_min"] / 60.0
df["avg_speed_mph"] = (df["trip_distance"] / duration_hours).round(2)

In [43]:
df

,PassengerCount,TripDistance,StoreAndFwdFlag,FareAmount,Extra,MtaTax,TipAmount,TollsAmount,ImprovementSurcharge,TotalAmount,...,AvgSpeedMph,VendorKey,RatecodeKey,PaymentTypeKey,PULocationKey,DOLocationKey,PickupDateKey,DropoffDateKey,PickupTimeKey,DropoffTimeKey
0,1,1.72,N,17.70,1.00,0.50,0.00,0.00,1.00,22.70,...,5.21,2.00,1,2,183,79,20240101,20240101,5755,11743
1,1,1.80,N,10.00,3.50,0.50,3.75,0.00,1.00,18.75,...,16.36,1.00,1,1,137,233,20240101,20240101,300,936
2,1,4.70,N,23.30,3.50,0.50,3.00,0.00,1.00,31.30,...,15.74,1.00,1,1,233,79,20240101,20240101,1706,3501
3,1,1.40,N,10.00,3.50,0.50,2.00,0.00,1.00,17.00,...,10.12,1.00,1,1,79,208,20240101,20240101,3638,4456
4,1,0.80,N,7.90,3.50,0.50,3.20,0.00,1.00,16.10,...,7.87,1.00,1,1,208,145,20240101,20240101,4651,5257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2964619,1,3.18,N,15.77,0.00,0.50,2.00,0.00,1.00,21.77,...,22.13,2.00,1,5,105,260,20240131,20240131,234559,235436
2964620,1,4.00,N,18.40,1.00,0.50,2.34,0.00,1.00,25.74,...,16.27,1.00,1,5,111,233,20240131,20240131,231307,232752
2964621,1,3.33,N,19.97,0.00,0.50,0.00,0.00,1.00,23.97,...,10.52,2.00,1,5,208,25,20240131,20240131,231900,233800
2964622,1,3.06,N,23.88,0.00,0.50,5.58,0.00,1.00,33.46,...,10.29,2.00,1,5,105,13,20240131,20240131,230723,232514
2964623,1,8.10,N,32.40,7.75,0.50,7.29,6.94,1.00,55.88,...,32.23,1.00,1,5,135,75,20240131,20240201,235825,1330

In [28]:
df["congestion_surcharge"] = df["congestion_surcharge"].fillna(0.0)
df["Airport_fee"] = df["Airport_fee"].fillna(0.0)

In [29]:
# Database Connection Configuration
from sqlalchemy import create_engine
SERVER_NAME = "FATMAH"  
DATABASE_NAME = "NYC_Taxi_DW"
connection_string = (
    f"mssql+pyodbc://@{SERVER_NAME}/{DATABASE_NAME}"
    "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)
engine = create_engine(connection_string)

In [ ]:

vendors = pd.DataFrame(
    [
        {"VendorID": 1, "VendorName": "Creative Mobile Technologies, LLC"},
        {"VendorID": 2, "VendorName": "VeriFone Inc."},
    ]
)

payments = pd.DataFrame(
    [
        {"PaymentTypeID": 1, "PaymentDescription": "Credit card"},
        {"PaymentTypeID": 2, "PaymentDescription": "Cash"},
        {"PaymentTypeID": 3, "PaymentDescription": "No charge"},
        {"PaymentTypeID": 4, "PaymentDescription": "Dispute"},
        {"PaymentTypeID": 5, "PaymentDescription": "Unknown"},
        {"PaymentTypeID": 6, "PaymentDescription": "Voided trip"},
    ]
)

ratecodes = pd.DataFrame(
    [
        {"RatecodeID": 1, "RateDescription": "Standard rate"},
        {"RatecodeID": 2, "RateDescription": "JFK"},
        {"RatecodeID": 3, "RateDescription": "Newark"},
        {"RatecodeID": 4, "RateDescription": "Nassau or Westchester"},
        {"RatecodeID": 5, "RateDescription": "Negotiated flat rate"},
        {"RatecodeID": 6, "RateDescription": "Group ride"},
    ]
)

unique_locs = set(df["PULocationID"].dropna().unique()).union(
    set(df["DOLocationID"].dropna().unique())
)
loc_df = pd.DataFrame({"LocationID": [int(x) for x in unique_locs]})

with engine.begin() as conn:
    vendors.to_sql("Dim_Vendor", con=conn, if_exists="append", index=False)
    payments.to_sql(
        "Dim_PaymentType", con=conn, if_exists="append", index=False
    )
    ratecodes.to_sql("Dim_Ratecode", con=conn, if_exists="append", index=False)
    loc_df.to_sql("Dim_Location", con=conn, if_exists="append", index=False)


date_range = pd.date_range(start="2024-01-01", end="2024-12-31", freq="D")
dim_date = pd.DataFrame({"FullDate": date_range})
dim_date["DateKey"] = dim_date["FullDate"].dt.strftime("%Y%m%d").astype(int)
dim_date["Year"] = dim_date["FullDate"].dt.year
dim_date["Quarter"] = dim_date["FullDate"].dt.quarter
dim_date["QuarterName"] = "Q" + dim_date["Quarter"].astype(str)
dim_date["Month"] = dim_date["FullDate"].dt.month
dim_date["MonthName"] = dim_date["FullDate"].dt.month_name()
dim_date["DayOfMonth"] = dim_date["FullDate"].dt.day
dim_date["DayOfWeek"] = dim_date["FullDate"].dt.dayofweek + 1
dim_date["DayName"] = dim_date["FullDate"].dt.day_name()
dim_date["IsWeekend"] = dim_date["DayOfWeek"].isin([6, 7]).astype(int)
dim_date["IsHoliday"] = 0

time_range = pd.date_range(
    start="00:00:00", end="23:59:59", freq="s"
).time
dim_time = pd.DataFrame({"TimeValue": time_range})
dim_time["TimeKey"] = [
    int(t.strftime("%H%M%S")) for t in dim_time["TimeValue"]
]
dim_time["Hour"] = [t.hour for t in dim_time["TimeValue"]]
dim_time["Minute"] = [t.minute for t in dim_time["TimeValue"]]
dim_time["AmPm"] = [t.strftime("%p") for t in dim_time["TimeValue"]]

hours = dim_time["Hour"]
conditions = [
    (hours >= 5) & (hours < 12),
    (hours >= 12) & (hours < 17),
    (hours >= 17) & (hours < 22),
]
choices = ["Morning", "Afternoon", "Evening"]
dim_time["TimeBucket"] = np.select(conditions, choices, default="Night")

with engine.begin() as conn:
    dim_date.to_sql("Dim_Date", con=conn, if_exists="append", index=False)
    dim_time.to_sql("Dim_Time", con=conn, if_exists="append", index=False)

In [ ]:
vendor_map = pd.read_sql(
    "SELECT VendorKey, VendorID FROM Dim_Vendor", con=engine
).set_index("VendorID")["VendorKey"]
rate_map = pd.read_sql(
    "SELECT RatecodeKey, RatecodeID FROM Dim_Ratecode", con=engine
).set_index("RatecodeID")["RatecodeKey"]
pay_map = pd.read_sql(
    "SELECT PaymentTypeKey, PaymentTypeID FROM Dim_PaymentType", con=engine
).set_index("PaymentTypeID")["PaymentTypeKey"]
loc_map = pd.read_sql(
    "SELECT LocationKey, LocationID FROM Dim_Location", con=engine
).set_index("LocationID")["LocationKey"]

df["VendorKey"] = df["VendorID"].map(vendor_map)
df["RatecodeKey"] = df["RatecodeID"].map(rate_map)
df["PaymentTypeKey"] = df["payment_type"].map(pay_map)
df["PULocationKey"] = df["PULocationID"].map(loc_map)
df["DOLocationKey"] = df["DOLocationID"].map(loc_map)

df["PickupDateKey"] = (
    df["tpep_pickup_datetime"].dt.strftime("%Y%m%d").astype(int)
)
df["DropoffDateKey"] = (
    df["tpep_dropoff_datetime"].dt.strftime("%Y%m%d").astype(int)
)
df["PickupTimeKey"] = (
    df["tpep_pickup_datetime"].dt.strftime("%H%M%S").astype(int)
)
df["DropoffTimeKey"] = (
    df["tpep_dropoff_datetime"].dt.strftime("%H%M%S").astype(int)
)

df.rename(
    columns={
        "store_and_fwd_flag": "StoreAndFwdFlag",
        "passenger_count": "PassengerCount",
        "trip_distance": "TripDistance",
        "fare_amount": "FareAmount",
        "extra": "Extra",
        "mta_tax": "MtaTax",
        "tip_amount": "TipAmount",
        "tolls_amount": "TollsAmount",
        "improvement_surcharge": "ImprovementSurcharge",
        "congestion_surcharge": "CongestionSurcharge",
        "Airport_fee": "AirportFee",
        "total_amount": "TotalAmount",
        "trip_duration_min": "TripDurationMin",
        "avg_speed_mph": "AvgSpeedMph",
    },
    inplace=True,
)

fact_columns = [
    "VendorKey",
    "RatecodeKey",
    "PaymentTypeKey",
    "PULocationKey",
    "DOLocationKey",
    "PickupDateKey",
    "DropoffDateKey",
    "PickupTimeKey",
    "DropoffTimeKey",
    "StoreAndFwdFlag",
    "PassengerCount",
    "TripDistance",
    "FareAmount",
    "Extra",
    "MtaTax",
    "TipAmount",
    "TollsAmount",
    "ImprovementSurcharge",
    "CongestionSurcharge",
    "AirportFee",
    "TotalAmount",
    "TripDurationMin",
    "AvgSpeedMph",
]

drop_cols = [col for col in df.columns if col not in fact_columns]
df.drop(columns=drop_cols, inplace=True)

df.to_sql(
    name="Fact_TaxiTrips",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=50000,
)

In [39]:
# Ingest Error Logs into Audit Table
# Append isolated invalid records to Audit_TaxiErrors table
engine.dispose()
with engine.begin() as conn:
    df_errors.to_sql(
        name="Audit_TaxiErrors",
        con=conn,
        if_exists="append",
        index=False,
        chunksize=50000,
    )

In [ ]:
print(df.shape)

(2809542, 23)

In [33]:
float_cols = df.select_dtypes(include=['float64']).columns
df[float_cols] = df[float_cols].astype('float32')
int_cols = df.select_dtypes(include=['int64']).columns
df[int_cols] = df[int_cols].astype('int32')